# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Give Permissions
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload LoadBalacner
      uses: actions/upload-artifact@v3.0.0
      with:
        name: VelocityLoadBalancer Built On 17 JDK
        path: "build/libs/velocityloadbalancer-1.1.jar"
    - name: Release the build
      if: ${{ github.event_name == 'push' }}
      uses: ncipollo/release-action@v1.10.0
      with:
       artifacts: "build/libs/velocityloadbalancer-1.1.jar"
       body: ${{ join(github.event.commits.*.message, '\n') }}
       prerelease: true
       name: JDK 17 Dev-build
       tag: dev-build-jdk-17
